version: 2.1

parameters:
  update-parent:
    default: false
    type: boolean
  update-properties:
    default: false
    type: boolean    

jobs:
  package-maven:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: clean and package
            command: mvn clean package

  deploy-maven:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: deploy
            command: bash .circleci/bash-deploy.bash

  increment-version:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: increment
            command: bash .circleci/bash-increment-version.bash
  
  update-parent:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: update-parent
            command: bash .circleci/bash-update-parent.bash
            
  update-properties:
    docker:
        - image: maven:3.8.4-openjdk-17
    working_directory: /spring-parent-pom
    steps:
        - checkout

        - run:
            name: update-properties
            command: bash .circleci/bash-update-properties.bash            

workflows:
  version: 2
  package:
    when:
      not:
        or:
          - << pipeline.parameters.update-parent >>
          - << pipeline.parameters.update-properties >> 
    jobs:
      - package-maven:
          filters:
            branches:
              ignore:
                - master

  release:
    when:
      not:
        or:
          - << pipeline.parameters.update-parent >>
          - << pipeline.parameters.update-properties >> 
    jobs:
      - package-maven:
          filters:
            branches:
              only:
                - master
      - increment-version:
          requires:
            - package-maven
      - deploy-maven:
          requires:
            - increment-version
  
  update-parent:
    when: << pipeline.parameters.update-parent >>
    jobs:
      - update-parent:
          context:
              - update-dependencies-context
      
  update-properties:
    when: << pipeline.parameters.update-properties >>
    jobs:
      - update-properties:
          context:
              - update-dependencies-context
